mastodon.instance-base-url=https://mastodon.social

mastodon.oauth.client-id=${MASTODON_OAUTH_CLIENT_ID:changeme}
mastodon.oauth.client-secret=${MASTODON_OAUTH_CLIENT_SECRET:changeme}
mastodon.oauth.scopes=${MASTODON_OAUTH_SCOPES:read:statuses write:statuses read:accounts}

mastodon.oauth.auth-url=${mastodon.instance-base-url}/oauth/authorize
mastodon.oauth.token-url=${mastodon.instance-base-url}/oauth/token
