package com.team.mcp.auth;

import java.net.URI;
import java.net.URLEncoder;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import org.springframework.stereotype.Component;

/**
 * OAuth client adapted for Mastodon in Iteration-2.
 *
 * <p>It builds an authorization URL and exchanges an auth "code"
 * for an access token by calling the Mastodon OAuth endpoints.
 */
@Component
public final class TwitterOAuthClient {

  /** Mastodon instance base URL. */
  private static final String INSTANCE_BASE = "https://mastodon.social";

  /** OAuth authorization endpoint URL. */
  private static final String AUTH_URL = INSTANCE_BASE + "/oauth/authorize";

  /** OAuth token endpoint URL. */
  private static final String TOKEN_URL = INSTANCE_BASE + "/oauth/token";

  /** OAuth client identifier from the Mastodon app registration. */
  private static final String CLIENT_ID =
      "OEX3bN0-kIqiMLCf6ra5qOdVRJzUEQF8vIRJzxSIBYs";

  /** OAuth client secret from the Mastodon app registration. */
  private static final String CLIENT_SECRET =
      "EErz7ksqnk9SUng7ewSVe1mZZV13z0QwFf4iQaj6eFk";

  /** Local callback used by the controller. Must match app config. */
  public static final String CALLBACK =
      "http://localhost:8080/auth/callback";

  /** Scopes used when requesting authorization. */
  private static final String SCOPES =
      "read:statuses write:statuses read:accounts";

  /** Divisor for HTTP status class (e.g. 2xx, 4xx). */
  private static final int HTTP_STATUS_CLASS_DIVISOR = 100;

  /** Success HTTP status class (2xx). */
  private static final int HTTP_STATUS_SUCCESS_CLASS = 2;

  /** Synthetic access-token lifetime in seconds (24 hours). */
  private static final long ACCESS_TOKEN_EXPIRY_SECONDS = 24L * 60L * 60L;

  /** HTTP client used for token exchange. */
  private final HttpClient http = HttpClient.newHttpClient();

  /** Default constructor for Spring and tests. */
  public TwitterOAuthClient() {
    // all configuration is static for this course project
  }

  /**
   * Build an authorization URL for Mastodon.
   *
   * @param state CSRF state generated by the server
   * @return a URL that can be opened in a browser
   */
  public String buildAuthorizeUrl(final String state) {
    return AUTH_URL
        + "?response_type=code"
        + "&client_id=" + enc(CLIENT_ID)
        + "&redirect_uri=" + enc(CALLBACK)
        + "&scope=" + enc(SCOPES)
        + "&state=" + enc(state);
  }

  /**
   * Exchange an auth code for an access token by calling
   * Mastodon's /oauth/token endpoint.
   *
   * <p>This is the original Iteration-1 style API, kept for backward
   * compatibility. It internally calls the richer metadata method.
   *
   * @param code authorization code from callback
   * @return the access token string
   */
  public String exchangeCodeForAccessToken(final String code) {
    return exchangeWithMetadata(code).accessToken();
  }

  /**
   * Iteration-2: exchange code and return a small metadata record
   * (access token + synthetic expiry + scopes).
   *
   * <p>For Mastodon, the access token is typically long-lived; for this
   * course project we treat it as if it has a 24h lifetime so that
   * higher layers can reason about expiry/health.
   *
   * @param code authorization code from callback
   * @return OAuthTokens record with access token and metadata
   */
  public OAuthTokens exchangeWithMetadata(final String code) {
    try {
      final String form = "grant_type=authorization_code"
          + "&client_id=" + enc(CLIENT_ID)
          + "&client_secret=" + enc(CLIENT_SECRET)
          + "&redirect_uri=" + enc(CALLBACK)
          + "&code=" + enc(code);

      HttpRequest req = HttpRequest.newBuilder()
          .uri(URI.create(TOKEN_URL))
          .header("Content-Type", "application/x-www-form-urlencoded")
          .POST(HttpRequest.BodyPublishers.ofString(form))
          .build();

      HttpResponse<String> resp =
          http.send(req, HttpResponse.BodyHandlers.ofString());

      int status = resp.statusCode();
      String body = resp.body();

      if (status / HTTP_STATUS_CLASS_DIVISOR != HTTP_STATUS_SUCCESS_CLASS) {
        throw new IllegalStateException(
            "Token endpoint returned " + status + ": " + body);
      }

      // Very small JSON parse to extract "access_token"
      String marker = "\"access_token\":\"";
      int idx = body.indexOf(marker);
      if (idx < 0) {
        throw new IllegalStateException(
            "No access_token in response: " + body);
      }
      int start = idx + marker.length();
      int end = body.indexOf('"', start);
      if (end < 0) {
        throw new IllegalStateException(
            "Unterminated access_token field: " + body);
      }
      String access = body.substring(start, end);

      // For this project, we model:
      // - no refresh_token (Mastodon typically uses long-lived tokens)
      // - a synthetic 24h expiry so that higher layers can show health
      long expiresInSeconds = ACCESS_TOKEN_EXPIRY_SECONDS;

      return new OAuthTokens(access, null, expiresInSeconds, SCOPES);

    } catch (Exception ex) {
      throw new RuntimeException(
          "Failed to exchange code for access token", ex);
    }
  }

  private static String enc(final String s) {
    return URLEncoder.encode(s, StandardCharsets.UTF_8);
  }

  /**
   * Small value object representing tokens + metadata returned
   * by the OAuth exchange.
   *
   * @param accessToken the bearer token
   * @param refreshToken optional refresh token (unused for Mastodon)
   * @param expiresIn number of seconds until expiry (synthetic)
   * @param scope scopes string as returned/used in the app
   */
  public record OAuthTokens(
      String accessToken,
      String refreshToken,
      Long expiresIn,
      String scope
  ) { }
}

