spring:
  datasource:
    url: jdbc:h2:mem:mcp;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false

# Keep fake client in tests
app:
  fakeTwitter: true
  publisher:
    fixedDelay: 15000
