-- V3__audit.sql
-- Persistent audit table for MCP tools/call invocations

CREATE TABLE IF NOT EXISTS tool_call_audit (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rpc_method    VARCHAR(40)  NOT NULL,
  tool_name     VARCHAR(64),
  account_id    VARCHAR(64),
  ok            BOOLEAN      NOT NULL,
  duration_ms   BIGINT       NOT NULL,
  error_code    INT,
  error_message VARCHAR(255),
  created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_audit_time
  ON tool_call_audit (created_at);
